import type { EffectDefinition } from "@/effects/types";

// UI catalog only; pixel processing lives in the shared Rust GPU renderer.
const presets = [
	{
		type: "cinematic",
		name: "Cinematic",
		keywords: ["Màu điện ảnh", "Cinematic"],
		category: "Color presets",
		mode: 0,
		strength: 65,
		detail: false,
	},
	{
		type: "warm",
		name: "Warm",
		keywords: ["Tông ấm", "Warm"],
		category: "Color presets",
		mode: 1,
		strength: 60,
		detail: false,
	},
	{
		type: "cool",
		name: "Cool",
		keywords: ["Tông lạnh", "Cool"],
		category: "Color presets",
		mode: 2,
		strength: 60,
		detail: false,
	},
	{
		type: "vintage",
		name: "Vintage",
		keywords: ["Hoài cổ", "Vintage"],
		category: "Retro",
		mode: 3,
		strength: 80,
		detail: false,
	},
	{
		type: "sepia",
		name: "Sepia",
		keywords: ["Nâu cổ điển", "Sepia"],
		category: "Retro",
		mode: 4,
		strength: 90,
		detail: false,
	},
	{
		type: "monochrome",
		name: "Black and white",
		keywords: ["Đen trắng", "Black and white"],
		category: "Color presets",
		mode: 5,
		strength: 100,
		detail: false,
	},
	{
		type: "vivid",
		name: "Vivid",
		keywords: ["Rực rỡ", "Vivid"],
		category: "Color presets",
		mode: 6,
		strength: 65,
		detail: false,
	},
	{
		type: "faded",
		name: "Faded film",
		keywords: ["Phim bạc màu", "Faded film"],
		category: "Retro",
		mode: 7,
		strength: 75,
		detail: false,
	},
	{
		type: "pastel",
		name: "Pastel",
		keywords: ["Màu pastel", "Pastel"],
		category: "Color presets",
		mode: 8,
		strength: 75,
		detail: false,
	},
	{
		type: "sunset",
		name: "Sunset",
		keywords: ["Hoàng hôn", "Sunset"],
		category: "Color presets",
		mode: 9,
		strength: 80,
		detail: false,
	},
	{
		type: "vignette",
		name: "Vignette",
		keywords: ["Tối góc", "Vignette"],
		category: "Lighting",
		mode: 10,
		strength: 65,
		detail: true,
	},
	{
		type: "grain",
		name: "Film grain",
		keywords: ["Hạt phim", "Film grain"],
		category: "Retro",
		mode: 11,
		strength: 70,
		detail: true,
	},
	{
		type: "chromatic",
		name: "Chromatic aberration",
		keywords: ["Tách màu RGB", "Chromatic aberration"],
		category: "Stylize",
		mode: 12,
		strength: 80,
		detail: true,
	},
	{
		type: "pixelate",
		name: "Pixelate",
		keywords: ["Điểm ảnh", "Pixelate"],
		category: "Stylize",
		mode: 13,
		strength: 100,
		detail: true,
	},
	{
		type: "sharpen",
		name: "Sharpen",
		keywords: ["Tăng nét", "Sharpen"],
		category: "Lighting",
		mode: 14,
		strength: 50,
		detail: true,
	},
	{
		type: "emboss",
		name: "Emboss",
		keywords: ["Dập nổi", "Emboss"],
		category: "Stylize",
		mode: 15,
		strength: 100,
		detail: true,
	},
	{
		type: "posterize",
		name: "Posterize",
		keywords: ["Màu áp phích", "Posterize"],
		category: "Stylize",
		mode: 16,
		strength: 100,
		detail: true,
	},
	{
		type: "sketch",
		name: "Pencil sketch",
		keywords: ["Phác thảo chì", "Pencil sketch"],
		category: "Stylize",
		mode: 17,
		strength: 100,
		detail: true,
	},
	{
		type: "neon",
		name: "Neon edges",
		keywords: ["Viền neon", "Neon edges"],
		category: "Lighting",
		mode: 18,
		strength: 100,
		detail: true,
	},
	{
		type: "solarize",
		name: "Solarize",
		keywords: ["Đảo sáng", "Solarize"],
		category: "Stylize",
		mode: 19,
		strength: 100,
		detail: false,
	},
	{
		type: "invert-colors",
		name: "Invert colors",
		keywords: ["Âm bản", "Invert colors"],
		category: "Stylize",
		mode: 20,
		strength: 100,
		detail: false,
	},
	{
		type: "halftone",
		name: "Halftone",
		keywords: ["Chấm truyện tranh", "Halftone"],
		category: "Stylize",
		mode: 21,
		strength: 100,
		detail: true,
	},
	{
		type: "mirror",
		name: "Horizontal mirror",
		keywords: ["Gương ngang", "Horizontal mirror"],
		category: "Distort",
		mode: 22,
		strength: 100,
		detail: false,
	},
	{
		type: "fisheye",
		name: "Fisheye",
		keywords: ["Mắt cá", "Fisheye"],
		category: "Distort",
		mode: 23,
		strength: 80,
		detail: true,
	},
	{
		type: "dreamy",
		name: "Dreamy glow",
		keywords: ["Ánh sáng mơ màng", "Dreamy glow"],
		category: "Lighting",
		mode: 24,
		strength: 65,
		detail: true,
	},
	{
		type: "scanlines",
		name: "Scanlines",
		keywords: ["Vạch màn hình", "Scanlines"],
		category: "Retro",
		mode: 25,
		strength: 70,
		detail: true,
	},
	{
		type: "duotone",
		name: "Duotone",
		keywords: ["Hai tông màu", "Duotone"],
		category: "Color presets",
		mode: 26,
		strength: 90,
		detail: false,
	},
] as const;

export const stylizeDefinitions: EffectDefinition[] = presets.map((preset) => ({
	type: preset.type,
	name: preset.name,
	category: preset.category,
	keywords: [...preset.keywords],
	params: [
		{
			key: "intensity",
			label: "Strength",
			type: "number",
			default: preset.strength,
			min: 0,
			max: 100,
			step: 1,
		},
		...(preset.detail
			? [
					{
						key: "detail",
						label: "Detail",
						type: "number" as const,
						default: preset.type === "pixelate" ? 10 : 35,
						min: 1,
						max: 100,
						step: 1,
					},
				]
			: []),
	],
	renderer: {
		passes: [
			{
				shader: "stylize",
				uniforms: ({ effectParams: p }) => ({
					u_mode: preset.mode,
					u_amount: Number(p.intensity ?? preset.strength) / 100,
					u_detail: Number(p.detail ?? 35),
				}),
			},
		],
	},
}));
